# Generated by Django 6.0.4 on 2026-05-07 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_users',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='plan_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_hr', models.BooleanField(default=True)),
                ('has_inventory', models.BooleanField(default=True)),
                ('has_suppliers', models.BooleanField(default=True)),
                ('has_accounting', models.BooleanField(default=False)),
                ('has_reports', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('business', 'Business'), ('enterprise', 'Enterprise')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('months_paid', models.IntegerField(default=1)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='company.company')),
            ],
        ),
    ]
