# Generated by Django 6.0.4 on 2026-05-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_max_users_company_plan_company_plan_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='plan_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
