# Generated by Django 6.0.4 on 2026-05-11 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_plan_expires'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox (Testing)'), ('production', 'Production (Live)')], default='sandbox', max_length=20)),
                ('shortcode', models.CharField(blank=True, help_text='Your M-Pesa till or paybill number. e.g. 174379', max_length=20)),
                ('_consumer_key', models.TextField(blank=True, db_column='consumer_key')),
                ('_consumer_secret', models.TextField(blank=True, db_column='consumer_secret')),
                ('_passkey', models.TextField(blank=True, db_column='passkey')),
                ('callback_url', models.URLField(blank=True, help_text='e.g. https://erip-system.onrender.com/payments/mpesa-callback/')),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_settings', to='company.company')),
            ],
            options={
                'verbose_name': 'M-Pesa Settings',
                'verbose_name_plural': 'M-Pesa Settings',
            },
        ),
    ]
